// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmbpvvuxwuvxxqxkpazr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtYnB2dnV4d3V2eHhxeGtwYXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NDQ4NDAsImV4cCI6MjA1MDEyMDg0MH0.--Hg3Cf8JJa39W-_ZL7NAOzAkJ09OHm8anITi00ua00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);